### PR TITLE
Tuple fixes

### PR DESCRIPTION
**Pull request by Keruspe**

### CODE REVIEW

**Comment by Keruspe** [comment]
Current test is failing with a tuple containing only one combinator fails with

```
   Compiling cookie-factory v0.3.0-beta4 (/home/keruspe/Projects/rust/cookie-factory)
warning: unnecessary parentheses around function argument
    --> src/combinator/mod.rs:1167:23
     |
1167 |                 tuple((string("0123"))),
     |                       ^^^^^^^^^^^^^^^^ help: remove these parentheses
     |
     = note: #[warn(unused_parens)] on by default

error[E0277]: the trait bound `impl combinator::SerializeFn<_>: combinator::Tuple<_>` is not satisfied
    --> src/combinator/mod.rs:1167:17
     |
1167 |                 tuple((string("0123"))),
     |                 ^^^^^ the trait `combinator::Tuple<_>` is not implemented for `impl combinator::SerializeFn<_>`
     |
note: required by `combinator::tuple`
    --> src/combinator/mod.rs:1000:1
     |
1000 | pub fn tuple<W: Write, List: Tuple<W>>(l: List) -> impl SerializeFn<W> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

any idea @sdroege ?

**Comment by sdroege** [comment]
On 31 July 2019 13:02:53 EEST, Marc-Antoine Perennou <notifications@github.com> wrote:
>Current test is failing with a tuple containing only one combinator
>fails with
>
>```
>Compiling cookie-factory v0.3.0-beta4
>(/home/keruspe/Projects/rust/cookie-factory)
>warning: unnecessary parentheses around function argument
>    --> src/combinator/mod.rs:1167:23
>     |
>1167 |                 tuple((string("0123"))),
>|                       ^^^^^^^^^^^^^^^^ help: remove these parentheses
>     |
>     = note: #[warn(unused_parens)] on by default
>
>error[E0277]: the trait bound `impl combinator::SerializeFn<_>:
>combinator::Tuple<_>` is not satisfied
>    --> src/combinator/mod.rs:1167:17
>     |
>1167 |                 tuple((string("0123"))),
>|                 ^^^^^ the trait `combinator::Tuple<_>` is not
>implemented for `impl combinator::SerializeFn<_>`
>     |
>note: required by `combinator::tuple`
>    --> src/combinator/mod.rs:1000:1
>     |
>1000 | pub fn tuple<W: Write, List: Tuple<W>>(l: List) -> impl
>SerializeFn<W> {
>|
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
>error: aborting due to previous error
>```
>
>any idea @sdroege ?

Yeah I intentionally left out the one element tuple, just like in nom. You think it's useful to have? When?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Keruspe** [comment]
When using tuple from generates code

**Comment by sdroege** [comment]
> When using tuple from generates code

Makes sense I guess. You want to add that missing impl? I think it should also be added to nom for consistency then (maybe @Geal has opinions?).

**Comment by Keruspe** [comment]
I sonny know. For my use case I basically enrolled what Tuple does in the
end

**Comment by sdroege** [comment]
Ok so what do we do about this one here then? :)

**Comment by Geal** [comment]
fixed in 136e174

**Comment by sdroege** [comment]
@Geal Will you also fix that in nom?

**Comment by Geal** [comment]
@sdroege yes: https://github.com/Geal/nom/commit/9d49820063f899fb711437913bdc414ced4fad91

**Comment by sdroege** [comment]
Great, thanks a lot :) Also for getting a release out

**Pull request closed without merging**
