### PR TITLE
Add tuple combinator

### PR DESCRIPTION
**Pull request by sdroege**
Depends on https://github.com/rust-bakery/cookie-factory/pull/20, which in turn depends on https://github.com/rust-bakery/cookie-factory/pull/19

Once those two PRs are merged, I'd rebase this one here and add docs, etc.

Macro code is adapted from nom (of course!) but quite a bit simpler for this case.

CC @Keruspe @Geal

### CODE REVIEW

**Comment by sdroege** [comment]
My use case for this is btw to write out a whole struct of values of different types. With `all` they would've to be all the same type, and from a readability point of view a tuple is much nicer to read than something with iterators.

It's also symmetric with nom. For these types my nom parser would look almost literally the same as the cookie-factory serializer.

**Comment by sdroege** [comment]
The various `fn_*` functions in `tests/http/mod.rs` could benefit from this too. It would allow to build them from combinators instead of imperatively.

**Comment by sdroege** [comment]
This should be ready now

**Comment by Keruspe** [comment]
Some comment wrt the macros could be useful, like an example of the generated code for (foo, bar, baz) or such

**Comment by sdroege** [comment]
Added comments to the macros about what they exactly do. Together with https://github.com/rust-bakery/cookie-factory/issues/23 we might also want to move things to individual files instead of having the `mod.rs` as a dumping ground for everything, but I'd prefer to do that as a separate PR afterwards once we have a clear plan how the module layout should look like in general.

**Comment by sdroege** [comment]
Independent of that, I'd like to have a combintor for [this](https://github.com/rust-bakery/cookie-factory/blob/8564c9dd6efb6f246b6048d3700e654293dfc061/tests/json/mod.rs#L66-L74). Some kind of match combinator. But I'm not sure how that would be possible :)

**Comment by Keruspe** [comment]
Thanks, looks nice!

Not sure either wrt the match stuff

**Comment by sdroege** [comment]
> Not sure either wrt the match stuff

Maybe @Geal has a non-macro idea? Otherwise, writing a macro for that is not too hard.

**Comment by sdroege** [comment]
Also thanks for the reviews and merging!

**Comment by sdroege** [comment]
Can you release another beta on crates.io with these changes?

What are the other things left to be done before a real release? https://github.com/rust-bakery/cookie-factory/issues/23?

**Comment by Geal** [comment]
I just published a beta4. Once we get #23 it should be ok for the release

**Pull request merged**
